[tool.poetry]
name = "frontend"
version = "0.1.0"
description = ""
authors = ["timmy <timtskm@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.12"
evaluate = "^0.4.3"
streamlit = "^1.45.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
